version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - apt-get install -y unzip
      - apt-get update

  build:
    commands:
      - echo Build started on `date`
      - zip hello.zip ./app.py config.py Dockerfile 
   
artifacts:
  type: 
  files:
    - hello.zip
    - Dockerfile
    - app.py
    - config.py
    - kube.yaml
    - templates/index.html
