kind: Deployment
apiVersion: apps/v1
metadata:
  name: projapp
  namespace: default
  labels:
    app: app1
spec:
  replicas: 1
  selector:                #kube automatically assign the names
    matchLabels:
      app: projapp           #name should match- pyapp
  template:
    metadata:
     #name:                #it is already assigned
     labels:
       app: projapp
    spec:
     containers:
       - name: cont1
         image: projapp:latest
         imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: projapp-svc
  namespace: default
  #labels: optional
spec:
  type: NodePort
  selector:
    app: projapp                        #Label name of the pods where you want to send traffic(instead of IP's)
  ports:
    - name: cont1port
      port: 80                      #Port of the image which is defined earlier
      nodePort: 30023
